# Generated by Django 6.1 on 2026-09-19 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'catalog_subject',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=128)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='catalog.subject')),
            ],
            options={
                'db_table': 'catalog_topic',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='catalog.topic')),
            ],
            options={
                'db_table': 'catalog_subtopic',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('subject', 'slug'), name='uniq_topic_subject_slug'),
        ),
    ]
