# Generated by Django 6.1 on 2026-09-19 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=128, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('city_uz', models.CharField(blank=True, default='', max_length=128)),
                ('city_ru', models.CharField(blank=True, default='', max_length=128)),
                ('city_en', models.CharField(blank=True, default='', max_length=128)),
                ('established', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, default='')),
                ('description_uz', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'universities_university',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name_uz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(blank=True, default='', max_length=255)),
                ('name_en', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('duration_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('quota', models.PositiveIntegerField(blank=True, null=True)),
                ('grant_places', models.PositiveIntegerField(blank=True, null=True)),
                ('paid_places', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subjects', models.ManyToManyField(blank=True, related_name='directions', to='catalog.subject')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='universities.university')),
            ],
            options={
                'db_table': 'universities_direction',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('university', 'code'), name='uniq_direction_university_code')],
            },
        ),
    ]
