BANK = {
    "matematika": [
        {
            "q": {
                "uz": "3x + 7 = 22 tenglamani yeching.",
                "ru": "Решите уравнение 3x + 7 = 22.",
                "en": "Solve the equation 3x + 7 = 22.",
            },
            "opts": [{"uz": "x = 5", "en": "x = 5", "ru": "x = 5"}, {"uz": "x = 3", "en": "x = 3", "ru": "x = 3"}, {"uz": "x = 6", "en": "x = 6", "ru": "x = 6"}, {"uz": "x = 9", "en": "x = 9", "ru": "x = 9"}],
            "correct": 0,
            "exp": {"uz": "22 dan 7 ni ayiramiz: 3x = 15, so'ng 3 ga bo'lamiz: x = 5.", "ru": "Вычтем 7: 3x = 15, затем разделим на 3: x = 5.", "en": "Subtract 7 from 22: 3x = 15, then divide by 3: x = 5."},
            "diff": 1,
        },
        {
            "q": {"uz": "15 ning 20% ini toping.", "ru": "Найдите 20% от 15.", "en": "Find 20% of 15."},
            "opts": [{"uz": "4.5", "en": "4.5", "ru": "4,5"}, {"uz": "3", "en": "3", "ru": "3"}, {"uz": "5", "en": "5", "ru": "5"}, {"uz": "2.5", "en": "2.5", "ru": "2,5"}],
            "correct": 1,
            "exp": {"uz": "15 × 0.2 = 3.", "ru": "15 × 0,2 = 3.", "en": "15 × 0.2 = 3."},
            "diff": 1,
        },
        {
            "q": {"uz": "Kvadratning tomoni 6 sm. Uning perimetrini toping.", "ru": "Сторона квадрата 6 см. Найдите его периметр.", "en": "The side of a square is 6 cm. Find its perimeter."},
            "opts": [{"uz": "12 sm", "ru": "12 см", "en": "12 cm"}, {"uz": "24 sm", "ru": "24 см", "en": "24 cm"}, {"uz": "36 sm", "ru": "36 см", "en": "36 cm"}, {"uz": "18 sm", "ru": "18 см", "en": "18 cm"}],
            "correct": 1,
            "exp": {"uz": "Kvadratning perimetri 4 × a = 4 × 6 = 24 sm.", "ru": "Периметр квадрата 4 × a = 4 × 6 = 24 см.", "en": "The perimeter of a square is 4 × a = 4 × 6 = 24 cm."},
            "diff": 1,
        },
        {
            "q": {"uz": "Quyidagilardan qaysi biri tub son?", "ru": "Какое из следующих чисел является простым?", "en": "Which of the following is a prime number?"},
            "opts": [{"uz": "21", "en": "21", "ru": "21"}, {"uz": "27", "en": "27", "ru": "27"}, {"uz": "29", "en": "29", "ru": "29"}, {"uz": "39", "en": "39", "ru": "39"}],
            "correct": 2,
            "exp": {"uz": "29 faqat 1 va o'ziga bo'linadi, qolganlari murakkab sonlar.", "ru": "29 делится только на 1 и себя, остальные — составные.", "en": "29 is only divisible by 1 and itself; the rest are composite numbers."},
            "diff": 1,
        },
        {
            "q": {"uz": "x² − 5x + 6 = 0 tenglamani yeching.", "ru": "Решите уравнение x² − 5x + 6 = 0.", "en": "Solve the equation x² − 5x + 6 = 0."},
            "opts": [{"uz": "x = 2 yoki x = 3", "ru": "x = 2 или x = 3", "en": "x = 2 or x = 3"}, {"uz": "x = 1 yoki x = 6", "ru": "x = 1 или x = 6", "en": "x = 1 or x = 6"}, {"uz": "x = −2 yoki x = −3", "ru": "x = −2 или x = −3", "en": "x = −2 or x = −3"}, {"uz": "x = 0 yoki x = 5", "ru": "x = 0 или x = 5", "en": "x = 0 or x = 5"}],
            "correct": 0,
            "exp": {"uz": "(x − 2)(x − 3) = 0, demak x = 2 yoki x = 3.", "ru": "(x − 2)(x − 3) = 0, значит x = 2 или x = 3.", "en": "(x − 2)(x − 3) = 0, so x = 2 or x = 3."},
            "diff": 2,
        },
        {
            "q": {"uz": "Agar sonning 3/4 qismi 18 bo'lsa, sonning o'zini toping.", "ru": "Если 3/4 числа равны 18, найдите само число.", "en": "If 3/4 of a number is 18, find the number."},
            "opts": [{"uz": "22", "en": "22", "ru": "22"}, {"uz": "24", "en": "24", "ru": "24"}, {"uz": "27", "en": "27", "ru": "27"}, {"uz": "21", "en": "21", "ru": "21"}],
            "correct": 1,
            "exp": {"uz": "18 ÷ 3 × 4 = 24.", "ru": "18 ÷ 3 × 4 = 24.", "en": "18 ÷ 3 × 4 = 24."},
            "diff": 2,
        },
        {
            "q": {"uz": "To'g'ri burchakli uchburchakning katetlari 6 va 8 sm. Gipotenuzani toping.", "ru": "Катеты прямоугольного треугольника 6 и 8 см. Найдите гипотенузу.", "en": "The legs of a right triangle are 6 and 8 cm. Find the hypotenuse."},
            "opts": [{"uz": "10 sm", "ru": "10 см", "en": "10 cm"}, {"uz": "12 sm", "ru": "12 см", "en": "12 cm"}, {"uz": "14 sm", "ru": "14 см", "en": "14 cm"}, {"uz": "9 sm", "ru": "9 см", "en": "9 cm"}],
            "correct": 0,
            "exp": {"uz": "Gipotenuza² = 6² + 8² = 100, gipotenuza = 10 sm.", "ru": "Гипотенуза² = 6² + 8² = 100, гипотенуза = 10 см.", "en": "Hypotenuse² = 6² + 8² = 100, hypotenuse = 10 cm."},
            "diff": 2,
        },
        {
            "q": {"uz": "Agar f(x) = 2x − 3 bo'lsa, f(5) ni toping.", "ru": "Если f(x) = 2x − 3, найдите f(5).", "en": "If f(x) = 2x − 3, find f(5)."},
            "opts": [{"uz": "7", "en": "7", "ru": "7"}, {"uz": "10", "en": "10", "ru": "10"}, {"uz": "13", "en": "13", "ru": "13"}, {"uz": "8", "en": "8", "ru": "8"}],
            "correct": 0,
            "exp": {"uz": "f(5) = 2 × 5 − 3 = 10 − 3 = 7.", "ru": "f(5) = 2 × 5 − 3 = 10 − 3 = 7.", "en": "f(5) = 2 × 5 − 3 = 10 − 3 = 7."},
            "diff": 2,
        },
        {
            "q": {"uz": "45 sonining bo'luvchilar sonini toping.", "ru": "Найдите количество делителей числа 45.", "en": "Find the number of divisors of 45."},
            "opts": [{"uz": "4", "en": "4", "ru": "4"}, {"uz": "6", "en": "6", "ru": "6"}, {"uz": "8", "en": "8", "ru": "8"}, {"uz": "5", "en": "5", "ru": "5"}],
            "correct": 1,
            "exp": {"uz": "45 = 3² × 5. Bo'luvchilar soni (2+1)(1+1) = 6.", "ru": "45 = 3² × 5. Количество делителей (2+1)(1+1) = 6.", "en": "45 = 3² × 5. Number of divisors is (2+1)(1+1) = 6."},
            "diff": 3,
        },
        {
            "q": {"uz": "A(2; 3) va B(6; 6) nuqtalar orasidagi masofani toping.", "ru": "Найдите расстояние между точками A(2; 3) и B(6; 6).", "en": "Find the distance between points A(2; 3) and B(6; 6)."},
            "opts": [{"uz": "4", "en": "4", "ru": "4"}, {"uz": "5", "en": "5", "ru": "5"}, {"uz": "7", "en": "7", "ru": "7"}, {"uz": "√10", "en": "√10", "ru": "√10"}],
            "correct": 1,
            "exp": {"uz": "d = √((6−2)² + (6−3)²) = √(16+9) = √25 = 5.", "ru": "d = √((6−2)² + (6−3)²) = √(16+9) = √25 = 5.", "en": "d = √((6−2)² + (6−3)²) = √(16+9) = √25 = 5."},
            "diff": 2,
        },
        {
            "q": {"uz": "Arifmetik progressiyada a₁ = 3, d = 2. a₅ ni toping.", "ru": "В арифметической прогрессии a₁ = 3, d = 2. Найдите a₅.", "en": "In an arithmetic progression a₁ = 3, d = 2. Find a₅."},
            "opts": [{"uz": "11", "en": "11", "ru": "11"}, {"uz": "13", "en": "13", "ru": "13"}, {"uz": "9", "en": "9", "ru": "9"}, {"uz": "15", "en": "15", "ru": "15"}],
            "correct": 0,
            "exp": {"uz": "a₅ = a₁ + 4d = 3 + 8 = 11.", "ru": "a₅ = a₁ + 4d = 3 + 8 = 11.", "en": "a₅ = a₁ + 4d = 3 + 8 = 11."},
            "diff": 2,
        },
        {
            "q": {"uz": "log₂(8) + log₂(4) ni hisoblang.", "ru": "Вычислите log₂(8) + log₂(4).", "en": "Evaluate log₂(8) + log₂(4)."},
            "opts": [{"uz": "5", "en": "5", "ru": "5"}, {"uz": "4", "en": "4", "ru": "4"}, {"uz": "6", "en": "6", "ru": "6"}, {"uz": "3", "en": "3", "ru": "3"}],
            "correct": 0,
            "exp": {"uz": "log₂8 = 3, log₂4 = 2, yig'indi 5.", "ru": "log₂8 = 3, log₂4 = 2, сумма 5.", "en": "log₂8 = 3, log₂4 = 2, the sum is 5."},
            "diff": 3,
        },
    ],
    "ona-tili-va-adabiyot": [
        {
            "q": {"uz": "Qaysi gapda ega qaratqich kelishigida?", "ru": "В каком предложении подлежащее стоит в родительном падеже?", "en": "In which sentence is the subject in the genitive case?"},
            "opts": [{"uz": "Akamning kitobi qiziqarli.", "ru": "Книга брата интересная.", "en": "My brother's book is interesting."}, {"uz": "Kitob stolda turibdi.", "ru": "Книга лежит на столе.", "en": "The book is on the table."}, {"uz": "Men kitob o'qidim.", "ru": "Я читал книгу.", "en": "I read a book."}, {"uz": "Kitobni do'stimga berdim.", "ru": "Я отдал книгу другу.", "en": "I gave the book to my friend."}],
            "correct": 0,
            "exp": {"uz": "«Akamning» so'zi qaratqich kelishigidagi ega — ot + -ning.", "ru": "«Akamning» — подлежащее в родительном падеже: существительное + -ning.", "en": "“Akamning” is a genitive-case subject — noun + -ning."},
            "diff": 2,
        },
        {
            "q": {"uz": "«Bilim — baxt eshigi» gapida tire nima uchun qo'yilgan?", "ru": "Почему в предложении «Bilim — baxt eshigi» стоит тире?", "en": "Why is a dash used in “Bilim — baxt eshigi”?"},
            "opts": [{"uz": "Ega va kesim orasida bog'lovchi tushib qolgan", "ru": "Между подлежащим и сказуемым пропущена связка", "en": "The copula between subject and predicate is omitted"}, {"uz": "Kirish so'zdan keyin", "ru": "После вводного слова", "en": "After an introductory word"}, {"uz": "Undalmani ajratish uchun", "ru": "Для выделения обращения", "en": "To separate a vocative"}, {"uz": "Iborani ajratish uchun", "ru": "Для выделения оборота", "en": "To separate a phrase"}],
            "correct": 0,
            "exp": {"uz": "Ega va ot kesim orasida «yaxlit» bog'lovchisi tushirilganda tire qo'yiladi.", "ru": "Тире ставится между подлежащим и именным сказуемым при пропуске связки.", "en": "A dash is placed when the copula between subject and nominal predicate is omitted."},
            "diff": 2,
        },
        {
            "q": {"uz": "Quyidagi so'zlarning qaysi birida «x» tovushi «v» ga yaqin talaffuz qilinadi?", "ru": "В каком из следующих слов звук «x» произносится близко к «в»?", "en": "In which word is the letter “x” pronounced close to “v”?"},
            "opts": [{"uz": "Xabar", "ru": "Xabar", "en": "Xabar"}, {"uz": "Xavfli", "ru": "Xavfli", "en": "Xavfli"}, {"uz": "Xarita", "ru": "Xarita", "en": "Xarita"}, {"uz": "Xo'roz", "ru": "Xo'roz", "en": "Xo'roz"}],
            "correct": 1,
            "exp": {"uz": "«Xavfli» so'zida «xv» birikmasida x v ga yaqin talaffuz qilinadi.", "ru": "В слове «Xavfli» в сочетании «xv» звук x произносится близко к v.", "en": "In “Xavfli” the cluster “xv” makes x sound close to v."},
            "diff": 3,
        },
        {
            "q": {"uz": "«Mehnatkash» so'zining yasalish usuli qaysi?", "ru": "Каким способом образовано слово «mehnatkash»?", "en": "How is the word “mehnatkash” formed?"},
            "opts": [{"uz": "Suffiksal (qo'shimcha) usul", "ru": "Суффиксальный способ", "en": "By suffixation"}, {"uz": "Prefiksal usul", "ru": "Префиксальный способ", "en": "By prefixation"}, {"uz": "Juftlash usuli", "ru": "Способ сложения", "en": "By compounding"}, {"uz": "Til birliklarining qo'shilishi", "ru": "Сращивание", "en": "By blending"}],
            "correct": 0,
            "exp": {"uz": "«Mehnat» o'zagi + «-kash» qo'shimchasi: suffiksal usul.", "ru": "Корень «mehnat» + суффикс «-kash»: суффиксальный способ.", "en": "Root “mehnat” + suffix “-kash”: suffixation."},
            "diff": 2,
        },
        {
            "q": {"uz": "Qaysi qatorda faqat ikkinchi shaxs kishilik olmoshlari berilgan?", "ru": "В каком ряду только местоимения второго лица?", "en": "Which row contains only second-person personal pronouns?"},
            "opts": [{"uz": "sen, siz", "ru": "sen, siz", "en": "sen, siz"}, {"uz": "men, sen", "ru": "men, sen", "en": "men, sen"}, {"uz": "u, ular", "ru": "u, ular", "en": "u, ular"}, {"uz": "biz, ular", "ru": "biz, ular", "en": "biz, ular"}],
            "correct": 0,
            "exp": {"uz": "Ikkinchi shaxs olmoshlari: sen va siz.", "ru": "Местоимения второго лица: sen и siz.", "en": "Second-person pronouns: sen and siz."},
            "diff": 1,
        },
        {
            "q": {"uz": "«Ko'zlari quvonganidan yig'lab yubordi» gapidagi kesim qanday ifodalangan?", "ru": "Чем выражено сказуемое в этом предложении?", "en": "What is the predicate in this sentence?"},
            "opts": [{"uz": "Fe'l birikmasi", "ru": "Глагольным сочетанием", "en": "A verb phrase"}, {"uz": "Ot", "ru": "Существительным", "en": "A noun"}, {"uz": "Sifat", "ru": "Прилагательным", "en": "An adjective"}, {"uz": "Ravish", "ru": "Наречием", "en": "An adverb"}],
            "correct": 0,
            "exp": {"uz": "Kesim «yig'lab yubordi» — fe'l birikmasi.", "ru": "Сказуемое «yig'lab yubordi» — глагольное сочетание.", "en": "The predicate “yig'lab yubordi” is a verb phrase."},
            "diff": 2,
        },
        {
            "q": {"uz": "Qaysi so'zda «ng» tovush birikmasi mavjud?", "ru": "В каком слове есть сочетание «ng»?", "en": "Which word contains the “ng” sound cluster?"},
            "opts": [{"uz": "Tanglay", "ru": "Tanglay", "en": "Tanglay"}, {"uz": "Sinov", "ru": "Sinov", "en": "Sinov"}, {"uz": "O'ng'ay", "ru": "O'ng'ay", "en": "O'ng'ay"}, {"uz": "Yangi", "ru": "Yangi", "en": "Yangi"}],
            "correct": 2,
            "exp": {"uz": "«O'ng'ay» so'zida ng tovush birikmasi bor (o'ng'ay).", "ru": "В слове «O'ng'ay» есть сочетание ng.", "en": "“O'ng'ay” contains the ng cluster."},
            "diff": 2,
        },
        {
            "q": {"uz": "«Nega kechiktirding?» gapida «nega» so'zi qaysi bo'lak?", "ru": "Каким членом предложения является слово «nega»?", "en": "What sentence part is “nega” in this question?"},
            "opts": [{"uz": "Sabab holi", "ru": "Обстоятельство причины", "en": "An adverbial of reason"}, {"uz": "To'ldiruvchi", "ru": "Дополнение", "en": "An object"}, {"uz": "Aniqlovchi", "ru": "Определение", "en": "An attribute"}, {"uz": "Ega", "ru": "Подлежащее", "en": "The subject"}],
            "correct": 0,
            "exp": {"uz": "«Nega» sabab holini bildiradi.", "ru": "«Nega» выражает обстоятельство причины.", "en": "“Nega” expresses an adverbial of reason."},
            "diff": 2,
        },
        {
            "q": {"uz": "O'zbek alifbosida jami nechta harf bor?", "ru": "Сколько букв в узбекском алфавите?", "en": "How many letters are in the Uzbek alphabet?"},
            "opts": [{"uz": "29", "en": "29", "ru": "29"}, {"uz": "26", "en": "26", "ru": "26"}, {"uz": "33", "en": "33", "ru": "33"}, {"uz": "32", "en": "32", "ru": "32"}],
            "correct": 0,
            "exp": {"uz": "O'zbek alifbosi 29 ta harfdan iborat.", "ru": "Узбекский алфавит состоит из 29 букв.", "en": "The Uzbek alphabet has 29 letters."},
            "diff": 1,
        },
        {
            "q": {"uz": "Qaysi gapda ko'chirma gap to'g'ri qo'llangan?", "ru": "В каком предложении прямая речь оформлена верно?", "en": "In which sentence is direct speech correctly punctuated?"},
            "opts": [{"uz": "U dedi: «Men bugun kelaman»", "ru": "Он сказал: «Я приду сегодня»", "en": "He said: “I will come today”"}, {"uz": "u dedi men bugun kelaman", "ru": "он сказал я приду сегодня", "en": "he said i will come today"}, {"uz": "U dedi: men bugun kelaman", "ru": "Он сказал: я приду сегодня", "en": "He said: i will come today"}, {"uz": "«Men bugun kelaman» u dedi", "ru": "«Я приду сегодня» он сказал", "en": "“I will come today” he said"}],
            "correct": 0,
            "exp": {"uz": "Ko'chirma gapdan keyin ikki nuqta va qo'shtirnoq belgilari to'g'ri qo'yilgan.", "ru": "После прямой речи верно поставлены двоеточие и кавычки.", "en": "Colon and quotation marks are correctly used after direct speech."},
            "diff": 2,
        },
    ],
    "ingliz-tili": [
        {
            "q": {"uz": "She ___ a doctor.", "ru": "Она ___ врач.", "en": "She ___ a doctor."},
            "opts": [{"uz": "is", "en": "is", "ru": "is"}, {"uz": "are", "en": "are", "ru": "are"}, {"uz": "am", "en": "am", "ru": "am"}, {"uz": "be", "en": "be", "ru": "be"}],
            "correct": 0,
            "exp": {"uz": "Uchinchi shaxs birlikda to be fe'lining is shakli ishlatiladi.", "ru": "В третьем лице единственного числа используется is.", "en": "Use is with a third-person singular subject."},
            "diff": 1,
        },
        {
            "q": {"uz": "Choose the correct plural form of “child”.", "ru": "Выберите правильную форму множественного числа слова child.", "en": "Choose the correct plural form of “child”."},
            "opts": [{"uz": "children", "en": "children", "ru": "children"}, {"uz": "childs", "en": "childs", "ru": "childs"}, {"uz": "childes", "en": "childes", "ru": "childes"}, {"uz": "childrens", "en": "childrens", "ru": "childrens"}],
            "correct": 0,
            "exp": {"uz": "child → children (istisno).", "ru": "child → children (исключение).", "en": "child → children (irregular)."},
            "diff": 1,
        },
        {
            "q": {"uz": "I have lived in Tashkent ___ 2015.", "ru": "Я живу в Ташкенте ___ 2015 года.", "en": "I have lived in Tashkent ___ 2015."},
            "opts": [{"uz": "since", "en": "since", "ru": "since"}, {"uz": "for", "en": "for", "ru": "for"}, {"uz": "from", "en": "from", "ru": "from"}, {"uz": "at", "en": "at", "ru": "at"}],
            "correct": 0,
            "exp": {"uz": "«2015» — aniq vaqt, shuning uchun since.", "ru": "«2015» — точка времени, поэтому since.", "en": "“2015” is a point in time, so we use since."},
            "diff": 2,
        },
        {
            "q": {"uz": "If it ___ tomorrow, we will stay at home.", "ru": "Если завтра ___ дождь, мы останемся дома.", "en": "If it ___ tomorrow, we will stay at home."},
            "opts": [{"uz": "rains", "en": "rains", "ru": "rains"}, {"uz": "will rain", "en": "will rain", "ru": "will rain"}, {"uz": "rained", "en": "rained", "ru": "rained"}, {"uz": "would rain", "en": "would rain", "ru": "would rain"}],
            "correct": 0,
            "exp": {"uz": "1-tip shart gapda: if + Present Simple.", "ru": "Первый тип условных: if + Present Simple.", "en": "First conditional: if + Present Simple."},
            "diff": 2,
        },
        {
            "q": {"uz": "Find the odd word out.", "ru": "Найдите лишнее слово.", "en": "Find the odd word out."},
            "opts": [{"uz": "apple", "en": "apple", "ru": "apple"}, {"uz": "banana", "en": "banana", "ru": "banana"}, {"uz": "carrot", "en": "carrot", "ru": "carrot"}, {"uz": "grape", "en": "grape", "ru": "grape"}],
            "correct": 2,
            "exp": {"uz": "Sabzi sabzavot, qolganlari meva.", "ru": "Морковь — овощ, остальные — фрукты.", "en": "Carrot is a vegetable; the rest are fruits."},
            "diff": 1,
        },
        {
            "q": {"uz": "She is good ___ playing chess.", "ru": "Она хорошо ___ играет в шахматы.", "en": "She is good ___ playing chess."},
            "opts": [{"uz": "at", "en": "at", "ru": "at"}, {"uz": "in", "en": "in", "ru": "in"}, {"uz": "on", "en": "on", "ru": "on"}, {"uz": "with", "en": "with", "ru": "with"}],
            "correct": 0,
            "exp": {"uz": "be good at + V-ing konstruksiyasi.", "ru": "Конструкция be good at + V-ing.", "en": "We use be good at + verb-ing."},
            "diff": 2,
        },
        {
            "q": {"uz": "Yesterday I ___ to the market.", "ru": "Вчера я ___ на рынок.", "en": "Yesterday I ___ to the market."},
            "opts": [{"uz": "went", "en": "went", "ru": "went"}, {"uz": "go", "en": "go", "ru": "go"}, {"uz": "gone", "en": "gone", "ru": "gone"}, {"uz": "goes", "en": "goes", "ru": "goes"}],
            "correct": 0,
            "exp": {"uz": "Yesterday → Past Simple → went.", "ru": "Yesterday → Past Simple → went.", "en": "“Yesterday” signals Past Simple, so we use went."},
            "diff": 1,
        },
        {
            "q": {"uz": "___ you like some tea?", "ru": "___ вы хотели бы чаю?", "en": "___ you like some tea?"},
            "opts": [{"uz": "Would", "en": "Would", "ru": "Would"}, {"uz": "Do", "en": "Do", "ru": "Do"}, {"uz": "Are", "en": "Are", "ru": "Are"}, {"uz": "Have", "en": "Have", "ru": "Have"}],
            "correct": 0,
            "exp": {"uz": "Taklif uchun Would you like...? ishlatiladi.", "ru": "Для предложения используется Would you like...?", "en": "Use “Would you like...?” for offers."},
            "diff": 2,
        },
    ],
    "fizika": [
        {
            "q": {"uz": "SI tizimida kuch birligi qaysi?", "ru": "Какая единица силы в системе СИ?", "en": "What is the SI unit of force?"},
            "opts": [{"uz": "Nyuton", "ru": "Ньютон", "en": "Newton"}, {"uz": "Joul", "ru": "Джоуль", "en": "Joule"}, {"uz": "Vatt", "ru": "Ватт", "en": "Watt"}, {"uz": "Paskal", "ru": "Паскаль", "en": "Pascal"}],
            "correct": 0,
            "exp": {"uz": "Kuch SI'da nyuton (N) bilan o'lchanadi.", "ru": "Сила в СИ измеряется в ньютонах (Н).", "en": "Force is measured in newtons (N) in the SI system."},
            "diff": 1,
        },
        {
            "q": {"uz": "Jismning tezligi v = 20 m/s. 5 soniyada qancha masofa bosib o'tadi?", "ru": "Скорость тела v = 20 м/с. Какое расстояние оно пройдёт за 5 секунд?", "en": "An object moves at v = 20 m/s. How far does it travel in 5 seconds?"},
            "opts": [{"uz": "100 m", "ru": "100 м", "en": "100 m"}, {"uz": "50 m", "ru": "50 м", "en": "50 m"}, {"uz": "25 m", "ru": "25 м", "en": "25 m"}, {"uz": "200 m", "ru": "200 м", "en": "200 m"}],
            "correct": 0,
            "exp": {"uz": "S = v × t = 20 × 5 = 100 m.", "ru": "S = v × t = 20 × 5 = 100 м.", "en": "S = v × t = 20 × 5 = 100 m."},
            "diff": 1,
        },
        {
            "q": {"uz": "Yorug'likning vakuumdagi tezligi taxminan qancha?", "ru": "Чему примерно равна скорость света в вакууме?", "en": "What is the approximate speed of light in a vacuum?"},
            "opts": [{"uz": "3 × 10⁸ m/s", "ru": "3 × 10⁸ м/с", "en": "3 × 10⁸ m/s"}, {"uz": "3 × 10⁶ m/s", "ru": "3 × 10⁶ м/с", "en": "3 × 10⁶ m/s"}, {"uz": "3 × 10⁷ m/s", "ru": "3 × 10⁷ м/с", "en": "3 × 10⁷ m/s"}, {"uz": "3 × 10⁵ m/s", "ru": "3 × 10⁵ м/с", "en": "3 × 10⁵ m/s"}],
            "correct": 0,
            "exp": {"uz": "Yorug'lik tezligi c ≈ 3 × 10⁸ m/s.", "ru": "Скорость света c ≈ 3 × 10⁸ м/с.", "en": "The speed of light is c ≈ 3 × 10⁸ m/s."},
            "diff": 1,
        },
        {
            "q": {"uz": "Nyutonning ikkinchi qonuni qanday ifodalanadi?", "ru": "Как выражается второй закон Ньютона?", "en": "How is Newton's second law expressed?"},
            "opts": [{"uz": "F = m·a", "ru": "F = m·a", "en": "F = m·a"}, {"uz": "F = m/a", "ru": "F = m/a", "en": "F = m/a"}, {"uz": "F = a/m", "ru": "F = a/m", "en": "F = a/m"}, {"uz": "F = m·v", "ru": "F = m·v", "en": "F = m·v"}],
            "correct": 0,
            "exp": {"uz": "Kuch = massa × tezlanish (F = m·a).", "ru": "Сила = масса × ускорение (F = m·a).", "en": "Force = mass × acceleration (F = m·a)."},
            "diff": 1,
        },
        {
            "q": {"uz": "Elektr tok kuchining SI birligi?", "ru": "Какая единица силы электрического тока в СИ?", "en": "What is the SI unit of electric current?"},
            "opts": [{"uz": "Amper", "ru": "Ампер", "en": "Ampere"}, {"uz": "Volt", "ru": "Вольт", "en": "Volt"}, {"uz": "Om", "ru": "Ом", "en": "Ohm"}, {"uz": "Kulon", "ru": "Кулон", "en": "Coulomb"}],
            "correct": 0,
            "exp": {"uz": "Tok kuchi SI'da amper (A) bilan o'lchanadi.", "ru": "Сила тока в СИ измеряется в амперах (А).", "en": "Electric current is measured in amperes (A) in SI."},
            "diff": 1,
        },
        {
            "q": {"uz": "Erkin tushuvchi jismning tezlanishi (g) taxminan qancha?", "ru": "Чему примерно равно ускорение свободного падения?", "en": "What is the acceleration due to gravity (g) approximately?"},
            "opts": [{"uz": "9.8 m/s²", "ru": "9,8 м/с²", "en": "9.8 m/s²"}, {"uz": "3.0 m/s²", "ru": "3,0 м/с²", "en": "3.0 m/s²"}, {"uz": "19.6 m/s²", "ru": "19,6 м/с²", "en": "19.6 m/s²"}, {"uz": "4.9 m/s²", "ru": "4,9 м/с²", "en": "4.9 m/s²"}],
            "correct": 0,
            "exp": {"uz": "Erkin tushish tezlanishi g ≈ 9.8 m/s².", "ru": "Ускорение свободного падения g ≈ 9,8 м/с².", "en": "The acceleration due to gravity is g ≈ 9.8 m/s²."},
            "diff": 1,
        },
        {
            "q": {"uz": "Quvvat qaysi formula bilan hisoblanadi?", "ru": "По какой формуле вычисляется мощность?", "en": "Which formula is used to calculate power?"},
            "opts": [{"uz": "P = A/t", "ru": "P = A/t", "en": "P = A/t"}, {"uz": "P = A·t", "ru": "P = A·t", "en": "P = A·t"}, {"uz": "P = m·g", "ru": "P = m·g", "en": "P = m·g"}, {"uz": "P = F·s", "ru": "P = F·s", "en": "P = F·s"}],
            "correct": 0,
            "exp": {"uz": "Quvvat = bajarilgan ish / vaqt (P = A/t).", "ru": "Мощность = работа / время (P = A/t).", "en": "Power = work done / time (P = A/t)."},
            "diff": 2,
        },
        {
            "q": {"uz": "Og'irligi 10 N bo'lgan jismning massasini toping (g = 10 m/s²).", "ru": "Найдите массу тела весом 10 Н (g = 10 м/с²).", "en": "Find the mass of a 10 N weight (g = 10 m/s²)."},
            "opts": [{"uz": "1 kg", "ru": "1 кг", "en": "1 kg"}, {"uz": "10 kg", "ru": "10 кг", "en": "10 kg"}, {"uz": "0.1 kg", "ru": "0,1 кг", "en": "0.1 kg"}, {"uz": "100 kg", "ru": "100 кг", "en": "100 kg"}],
            "correct": 0,
            "exp": {"uz": "m = P/g = 10/10 = 1 kg.", "ru": "m = P/g = 10/10 = 1 кг.", "en": "m = P/g = 10/10 = 1 kg."},
            "diff": 2,
        },
    ],
}