# Generated by Django 6.1.1 on 2026-09-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('tier', models.CharField(choices=[('free', 'Bepul'), ('pro', 'PRO')], db_index=True, default='pro', max_length=16)),
                ('name_uz', models.CharField(max_length=120)),
                ('name_ru', models.CharField(blank=True, default='', max_length=120)),
                ('name_en', models.CharField(blank=True, default='', max_length=120)),
                ('description_uz', models.TextField(blank=True, default='')),
                ('description_ru', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('price_uzs', models.PositiveIntegerField(default=0)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('max_sessions_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'premium_plan',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='premium.subscriptionplan')),
            ],
            options={
                'db_table': 'premium_subscription',
                'ordering': ['-created_at'],
            },
        ),
    ]
