# Generated by Django 6.1 on 2026-09-19 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField(blank=True, default='')),
                ('text_en', models.TextField(blank=True, default='')),
                ('question_type', models.CharField(choices=[('single', "Bitta to'g'ri javob"), ('multiple', "Bir nechta to'g'ri javob")], default='single', max_length=16)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Oson'), (2, "O'rta"), (3, 'Qiyin')], db_index=True, default=2)),
                ('explanation_uz', models.TextField(blank=True, default='')),
                ('explanation_ru', models.TextField(blank=True, default='')),
                ('explanation_en', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('dtm', 'DTM rasmiy'), ('bmb', 'BMB rasmiy'), ('custom', "O'qituvchi tuzgan"), ('unknown', "Noma'lum")], default='unknown', max_length=16)),
                ('is_official', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Qoralama'), ('published', 'Chop etilgan'), ('archived', 'Arxivlangan')], db_index=True, default='draft', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='catalog.subject')),
                ('subtopic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='catalog.subtopic')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='catalog.topic')),
            ],
            options={
                'db_table': 'questions_question',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField(blank=True, default='')),
                ('text_en', models.TextField(blank=True, default='')),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questions.question')),
            ],
            options={
                'db_table': 'questions_option',
                'ordering': ['sort_order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('question', 'sort_order'), name='uniq_option_question_order')],
            },
        ),
    ]
